name: Build/release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    env:
      STEAMWORKS_SDK_ARCHIVE_PASSWORD: ${{ secrets.STEAMWORKS_SDK_ARCHIVE_PASSWORD }}
      STEAMWORKS_SDK_GOOGLE_DRIVE_LINK: ${{ secrets.STEAMWORKS_SDK_GOOGLE_DRIVE_LINK }}
      STEAM_AUTH_FILES_GOOGLE_DRIVE_LINK: ${{ secrets.STEAM_AUTH_FILES_GOOGLE_DRIVE_LINK }}

    strategy:
      matrix:
        os: [windows-latest, linux-latest, macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps

      - name: Publish github releases
        env:
          # These values are used for auto updates signing
          # APPLE_ID: ${{ secrets.APPLE_ID }}
          # APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          # CSC_LINK: ${{ secrets.CSC_LINK }}
          # CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run postinstall
          npm run build
          npm exec electron-builder -- --publish always
          # npm exec electron-builder -- --publish always --win --mac --linux

      - name: Copy release build to steamworks_sdk "content" folder
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
                cp -r ./release/build/win-unpacked/. ./steamworks_sdk/tools/ContentBuilder/content/
          elif [ "$RUNNER_OS" == "Windows" ]; then
                cp -r ./release/build/linux-unpacked/. ./steamworks_sdk/tools/ContentBuilder/content/
          elif [ "$RUNNER_OS" == "macOS" ]; then
                cp -r ./release/build/macos-unpacked/. ./steamworks_sdk/tools/ContentBuilder/content/
          else
                echo "$RUNNER_OS not supported"
                exit 1
          fi

      - name: Create steamworks build script
        run: node ./scripts/createSteamBuildScript.js
        env:
          STEAM_APP_ID: 1904150
          RELEASE_BRANCH: development
          DEPOT_WINDOWS_ID: 1904151
          DEPOT_LINUX_ID: 1904152
          DEPOT_MACOS_ID: 1904153
          RUNNER_OS: $RUNNER_OS

      - name: Create auth files
        run: node ./scripts/fetchSteamAuthFiles.js

      - name: Steam build & release
        run: |
          "./steamworks_sdk/tools/ContentBuilder/builder/steamcmd.exe" +login ${{ secrets.STEAM_USERNAME }} ${{ secrets.STEAM_PASSWORD }} +run_app_build ../scripts/simple_build.vdf +quit
