name: Build/release

on:
  push
  # push:
  #   tags:
  #     - "*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    env:
      STEAMWORKS_SDK_ARCHIVE_PASSWORD: ${{ secrets.STEAMWORKS_SDK_ARCHIVE_PASSWORD }}
      STEAMWORKS_SDK_GOOGLE_DRIVE_LINK: ${{ secrets.STEAMWORKS_SDK_GOOGLE_DRIVE_LINK }}
      STEAM_AUTH_FILES_GOOGLE_DRIVE_LINK: ${{ secrets.STEAM_AUTH_FILES_GOOGLE_DRIVE_LINK }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps

      - name: Build
        run: |
          npm run postinstall
          npm run build

      # - name: Publish to github
      #   env:
      #     # These values are used for auto updates signing
      #     # APPLE_ID: ${{ secrets.APPLE_ID }}
      #     # APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
      #     # CSC_LINK: ${{ secrets.CSC_LINK }}
      #     # CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      #     # This is used for uploading release assets to github
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: npm exec electron-builder -- --publish always

      - id: setup-steamcmd
        uses: CyberAndrii/setup-steamcmd@v1.1.1

      - name: Create steamworks build script
        run: node ./scripts/createSteamBuildScript.js
        env:
          STEAM_APP_ID: 1904150
          RELEASE_BRANCH: development
          DEPOT_WINDOWS_ID: 1904151
          DEPOT_LINUX_ID: 1904152
          DEPOT_MACOS_ID: 1904153
          RUNNER_OS: $RUNNER_OS

      - name: Create auth files
        run: |
          echo "dir ${{ steps.setup-steamcmd.outputs.directory }}"
          echo "executable ${{ steps.setup-steamcmd.outputs.executable }}"
          node ./scripts/fetchSteamAuthFiles.js
          cd steam_auth_files
          ls
          cd ${{ steps.setup-steamcmd.outputs.directory }}
          ls
        env:
          STEAMCMD_DIR: ${{ steps.setup-steamcmd.outputs.directory }}

      - name: Publish to Steam
        run: |
          ${{ steps.setup-steamcmd.outputs.executable }} +login ${{ secrets.STEAM_USERNAME }} ${{ secrets.STEAM_PASSWORD }} +run_app_build ./steam_build.vdf +quit
