name: Test

on:
  push:
    branches:
      - "*"
      - "!main"
      - "!l10n_main"

env:
  STEAMWORKS_SDK_ARCHIVE_PASSWORD: ${{ secrets.STEAMWORKS_SDK_ARCHIVE_PASSWORD }}
  STEAMWORKS_SDK_GOOGLE_DRIVE_LINK: ${{ secrets.STEAMWORKS_SDK_GOOGLE_DRIVE_LINK }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - name: TEMPORARY - Install gdown for fetchSteamworksSdk.js
        run: pip3 install gdown
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Lint
        run: npm run lint

  lint-prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - name: TEMPORARY - Install gdown for fetchSteamworksSdk.js
        run: pip3 install gdown
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Lint Prettier
        run: npm run lint:prettier

  lint-types:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - name: TEMPORARY - Install gdown for fetchSteamworksSdk.js
        run: pip3 install gdown
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Lint Types
        run: npm run lint:types

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - name: TEMPORARY - Install gdown for fetchSteamworksSdk.js
        run: pip3 install gdown
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Test
        run: npm run test
