# name: Test

# on: [push, pull_request]

# jobs:
#   release:
#     runs-on: ${{ matrix.os }}

#     env:
#       STEAMWORKS_SDK_ARCHIVE_PASSWORD: ${{ secrets.STEAMWORKS_SDK_ARCHIVE_PASSWORD }}
#       STEAMWORKS_SDK_GOOGLE_DRIVE_LINK: ${{ secrets.STEAMWORKS_SDK_GOOGLE_DRIVE_LINK }}

#     strategy:
#       matrix:
#         os: [windows-latest]

#     steps:
#       - name: Check out Git repository
#         uses: actions/checkout@v3

#       - name: Install Node.js and NPM
#         uses: actions/setup-node@v3
#         with:
#           node-version: "16"
#           cache: "npm"

#       - name: Install dependencies
#         run: |
#           npm install

#       - name: npm test
#         env:
#           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
#         run: |
#           npm run package
#           npm run lint
#           npm exec tsc
#           npm test
